//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet4You.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTimeTable
    {
        public int Id { get; set; }
        public int Food_Id { get; set; }
        public System.DateTime FeedTime { get; set; }
        public Nullable<int> FoodWeightGramm { get; set; }
        public Nullable<int> Pet_Id { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Pet Pet { get; set; }
    }
}
