//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet4You.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int id { get; set; }
        public Nullable<int> ChatId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual User User { get; set; }
    }
}
