//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet4You.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pet4YouDemoEntities : DbContext
    {
        public Pet4YouDemoEntities()
            : base("name=Pet4YouDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityType> ActivityType { get; set; }
        public virtual DbSet<AnimalKind> AnimalKind { get; set; }
        public virtual DbSet<Breed> Breed { get; set; }
        public virtual DbSet<Chats> Chats { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<FoodBrand> FoodBrand { get; set; }
        public virtual DbSet<FoodTimeTable> FoodTimeTable { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Pet> Pet { get; set; }
        public virtual DbSet<Themes> Themes { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
